---
- name: Pipeline
  hosts: aws
  become: yes
  tasks:

  # sudo apt-get install *
  - name: Install docker packages
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    tags:
      - docker
  
  # curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - name: Add Dockers official GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    tags:
      - docker
  
  # sudo apt-key fingerprint 0EBFCD88
  - name: Verify that we have the key with the fingerprint
    apt_key:
      id: 0EBFCD88
      state: present
    tags:
      - docker
  
  # sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
  - name: Set up the stable repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present
      update_cache: yes
    tags:
      - docker
  
  # sudo apt-get update
  - name: Update apt packages
    apt:
      update_cache: yes
    tags:
      - docker
  
  # sudo apt-get install docker-ce=18.03.*
  - name: Install docker
    apt:
      name: docker-ce=18.03.*
      state: present
      update_cache: yes
    notify: Start docker on boot
    tags:
      - docker
  
  # sudo groupadd docker
  - name: Create "docker" group
    group:
      name: docker
      state: present
    tags:
      - docker
  
  # sudo usermod -aG docker ubuntu
  - name: Add remote "ubuntu" user to "docker" group
    user:
      name: ubuntu
      group: docker
      append: yes
    tags:
      - docker
  
  # sudo apt-get install docker-compose=1.8.*
  - name: Install docker-compose
    remote_user: ubuntu
    get_url: 
      url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 'u+x,g+x'

  #Copy de proyect
  - name: Copy file with owner and permissions
    copy:
      src: /var/lib/jenkins/repo
      dest: /home/ubuntu/proyect

  - name: Run `docker-compose up`
    shell:
      cmd: "docker-compose up -d"
      chdir: /home/ubuntu/proyect